### PR TITLE
keyboard-select arrow keys

### PR DESCRIPTION
**Pull request by CyberShadow**

### CODE REVIEW

**Comment by muennich** [comment]
Does vim have these arrow key mappings?

**Comment by CyberShadow** [comment]
I don't know, but they are standard on practically every Windows and WordStar-like editor (i.e. essentially everything except emacs/vim/nano).

**Comment by CyberShadow** [comment]
gvim has the ctrl+left/right keys at least.

**Comment by muennich** [comment]
I do not like how switching modifiers kind of breaks the selection mode. Using an arrow key with the Shift modifier initiates normal selection mode. Prior to your changes, using the arrow keys without a modifier in this mode extended the current selection, with your changes it exits selection mode. Also, after starting normal selection mode with Shift, selecting some more characters and then switching to blockwise selection is not possible simply by releasing the Shift and pressing the Alt modifier.

I'm really skeptic about making arrow keys with modifiers work with vi-like modal key mappings. It feels a bit like different worlds colliding.

**Comment by CyberShadow** [comment]
> Prior to your changes, using the arrow keys without a modifier in this mode extended the current selection, with your changes it exits selection mode.

Oops, that's not by design, just an oversight / bug. I'll add a transient selection flag if that's OK with you.

> Also, after starting normal selection mode with Shift, selecting some more characters and then switching to blockwise selection is not possible simply by releasing the Shift and pressing the Alt modifier.

That's just fine with me, as far as I know no editor that uses mod+arrowkey selection allows this anyway.

> I'm really skeptic about making arrow keys with modifiers work with vi-like modal key mappings. It feels a bit like different worlds colliding.

So far I don't see any non-resolvable conflicts, but if it were to come to that, it could be configurable, right? Besides, [vim itself can be configured to support this](https://www.google.com/search?q=vi+shift+select).

**Comment by muennich** [comment]
Please have a look at commit f24b3abb. I tried to address the shortcomings mentioned before; while trying to keep the diff to master as small as possible. I still don't like the behaviour of Ctrl-left/-right in selection mode.

**Comment by CyberShadow** [comment]
> Please have a look at commit f24b3ab. I tried to address the shortcomings mentioned before; while trying to keep the diff to master as small as possible.

Thanks, but there is no obvious way to stop selecting text, at least without using vim-specific keys or exiting keyboard-select.

> I still don't like the behaviour of Ctrl-left/-right in selection mode.

What's your concern?

**Comment by muennich** [comment]
There is no obvious way to stop selecting text apart from vi-specific key bindings, because that is the whole point of keyboard-select: vi-like modal key bindings. With your changes stopping selection mode was easier, but very vi-unlike. And actually copying the selected text still requires vi-like keys.

Ctrl-left/-right do not work the same way as in the url bar of firefox and chromium; these are the only GUI programs I have installed and therefore my only reference points. The cursor lands directly on a space or some other word delimiting character instead of the first/last character of a word as with my commit.

You are not going to like it, but I have to say it: Implementing the exact same arrow key behaviour in keyboard-select as in typical GUI programs requires much more work than that. Right from the start, everything was done with vi-like modal keybindings in mind. And I am unwilling to change these basics to support arrow key behaviour known from programs with a completely different set of key bindings. My commit resembles the amount of work/change that I am willing to include into keyboard-select for something of such low value for me and others used to vi-like key bindings.

**Comment by CyberShadow** [comment]
OK, so would you suggest that I maintain this in my own fork?

I understand if you don't want to maintain functionality you won't use, but I'm wondering if there is another fork I can contribute this to, or if there are other contributions that have been rejected on a similar basis that could be joined into a fork.

**Comment by muennich** [comment]
That's what makes Github so great and keeps everyone happy. Please take a look at the forks and the pull requests yourself to find the answers to your questions.

**Pull request closed without merging**
